trigger:
  - pipe

variables:
  FlutterChannel: 'stable'
  FlutterVersion: 'latest'

  ProjectSlug: 'nam.nvnnb-hotmail.com/tpos_mobile>'
  ProjectDirectory: '$(Build.SourcesDirectory)'

  BuildNumber: '$(Build.BuildNumber)'
  BuildMessage: '$(Build.SourceVersionMessage)'
  BuildDirectory: '$(ProjectDirectory)/build/app/outputs/apk/release/app-release.apk'

jobs:
  - job: Build
    pool:
      name: Default
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        displayName: Setup flutter
        inputs:
          channel: 'stable'
          version: 'latest'

      - task: FlutterBuild@0
        displayName: Run build
        inputs:
          target: 'apk'
          projectDirectory: '$(ProjectDirectory)'
          buildName: '$(BuildName)'
          buildNumber: '$(BuildNumber)'

      - task: CopyFiles@2
        inputs:
          contents: '**/*.apk'
          targetFolder: '$(build.artifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
