name: tpos_mobile
description: Phiên bản mobile của phần mờm bán hàng TPos.

version: 1.8.0+150
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_emoji_keyboard: ^0.1.3
  http: ^0.12.2 #Request, Get, post, put, delete
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.4.11
  flutter_facebook_login: ^3.0.0 #Login facebook
  scoped_model: ^1.1.0
  provider: ^4.3.2+2
  intl: 0.16.1 # Format datetime, number
  w3c_event_source: ^1.3.2 # Capture server send event
  diacritic: ^0.1.1 #remove mark
  test: ^1.5.1+1
  font_awesome_flutter: ^8.5.0
  datetime_picker_formfield: ^1.0.0
  timeago: ^2.0.22
  logging: ^0.11.3+2
  logger: ^0.9.4
  sentry: ^3.0.0+1
  rxdart: ^0.24.1
  #rx_command: ^5.2.1 | Remove from version 1.8.0
  screen: ^0.0.5
  package_info: ^0.4.3+2
  image_picker: ^0.6.2+3
  device_info:  ^1.0.0
  cached_network_image: ^2.2.3
  badges: ^1.1.4
  firebase_core: ^0.7.0
  firebase_remote_config: ^0.6.0
  firebase_crashlytics: ^0.4.0+1
  firebase_analytics: ^7.0.1
  firebase_messaging: ^8.0.0-dev.14
  cloud_firestore: ^0.16.0
  webview_flutter: ^1.0.7
  signalr_client: ^0.1.6
  hex: ^0.1.2
  pdf: ^1.11.2
  printing: ^3.7.1
  random_color: ^1.0.3
  store_redirect: ^1.0.2
  date_range_picker: ^1.0.6
  flutter_masked_text: ^0.8.0
  async: ^2.4.2
  circular_check_box: ^1.0.4
  flutter_spinkit: ^4.1.2
  sticky_headers: ^0.1.8+1 #Làm header của một list luôn "dính" trên màn hình
  fl_chart: ^0.12.0 #Biểu đồ bánh(Pie Chart) và đường (Line Chart)
  auto_size_text: ^2.1.0 #Tự điờu chỉnh size chữ nhờ lại khi không đủ không gianp
  flutter_charts: ^0.1.10 #Biểu đồ cột
  flutter_screenutil: ^3.2.0 #căn chỉnh kích thước theo thiết bị
  flutter_svg: ^0.19.1
  barcode_flutter: ^1.1.2
  network_image_to_byte: ^0.0.1
  animated_background: ^1.0.5
  flutter_slidable: ^0.5.4
  mockito: ^4.1.1
  version: ^1.2.0
  sqflite: ^1.1.0
  path_provider: ^1.6.24
  dio: ^3.0.10
  equatable: ^1.2.5
  google_fonts: ^1.1.1
  flushbar: ^1.10.4
  permission_handler: ^5.0.1+1
  flutter_datetime_picker: ^1.4.0
  open_file: ^3.0.3
  qr_flutter: ^3.2.0
  reorderables: ^0.3.2
  flutter_bloc: ^6.1.1
  get_it: ^5.0.1
  lottie: ^0.7.0+1
  flutter_html: ^1.0.2
  animations: ^1.1.2
  pull_to_refresh: 1.6.2
  get: any
  draggable_scrollbar: ^0.0.4
  scroll_to_index: ^1.0.6
  dotted_border: ^1.0.6
  flutter_swiper: ^1.1.6
  multi_image_picker: ^4.7.14
  photo_manager: ^0.5.8
  qr_code_scanner: ^0.0.13
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  shimmer: ^1.1.2
  wifi: ^0.1.5
  device_preview: ^0.5.5
  flutter_local_notifications: ^3.0.3
  connectivity: ^2.0.2
  tpos_api_client:
    path: ../tpos_api_client
  facebook_api_client:
    path: ../facebook_api_client
  tpos_mobile_localization:
    path: ../tpos_mobile_localization
  camera_with_rtmp:
      path: ../PACKAGE/camera_with_rtmp-0.3.2
#  tmt_flutter_viewmodel:
#    path : ../../PACKAGE/tmt_flutter_viewmodel
#  tmt_flutter_ui:
#    path: ../../PACKAGE/tmt_flutter_ui
  nam_esc_pos_printer:
    git:
      url: https://tfs.tpos.dev/TMT01Collection/TMT%20Flutter%20Gallery/_git/nam_esc_pos_printer
      ref: v1.4.12

  tmt_flutter_untils:
    git:
      url: https://tfs.tpos.dev/TMT01Collection/TMT%20Flutter%20Gallery/_git/tmt_flutter_utils
      ref: master

  tmt_flutter_ui:
    git:
      url: https://tfs.tpos.dev/TMT01Collection/TMT%20Flutter%20Gallery/_git/tmt_flutter_ui
      ref: master
  tmt_flutter_viewmodel:
    git:
      url: https://tfs.tpos.dev/TMT01Collection/TMT%20Flutter%20Gallery/_git/tmt_flutter_viewmodel
      ref: master

#  barcode_scan:
#      path : ../barcode_scan-3.0.1
dependency_overrides:
  webview_flutter: '1.0.7'
dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/tpos_mobile_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
    - assets/lottie/
    - assets/icon/insert_image.svg
    - assets/icon/variant.svg
    - assets/icon/error.svg
    - assets/icon/upload.svg
    - assets/icon/download.svg
    - assets/icon/empty-image-product.svg
    - assets/icon/close.svg
    - assets/icon/refresh.svg
    - assets/icon/empty-data.svg
    - assets/icon/tag_green.svg
    - assets/icon/win.svg
    - assets/icon/person.svg
    - assets/icon/share.svg
    - assets/icon/delete.svg
    - assets/icon/comment.svg
    - assets/icon/game_wheel_arrow.svg
    - assets/icon/rotate_screen.svg
    - assets/icon/instruction.svg
    - assets/icon/messenger.svg
    - assets/icon/congratulation.svg
    - assets/icon/product_name.svg
    - assets/svg/
    - assets/game/icon/
    - images/error.png
    - images/empty.png
    - images/tpos_logo.png
    - images/app_bar_background.png
    - images/no_image.png
    - images/facebook_play.png
    - images/tpos_logo_180.png
    - images/tpos_logo_512.png
    - images/tpos_mobile_icon.png
    - images/tpos_logo_512x512.png
    - images/arrow.png
    - images/game_title.png
    - images/game_avatar.jfif
    - images/game_luckywheel_avatar_white.jpg
    - images/test_print_image.png
    - images/testPrinter.png
    - images/barcode_scan.svg
    - images/avatar_50x.png
    - images/star_stroke.png
    - images/ballon.png
    - images/vnpost_logo.png
    - images/viettelpost_logo.png
    - images/giaohangnhanh_logo.png
    - images/giaohangtietkiem_logo.png
    - images/fixed_price.jpg
    - images/tintoc_logo.jpg
    - images/jt_logo.jpg
    - images/supership_logo.png
    - images/empty_state.flr
    - images/delivery-truck.svg
    - images/factory.png
    - images/customer.png
    - images/customer_group.svg
    - images/receipt.svg
    - images/like.png
    - images/order_bill.png
    - images/export.png
    - images/import.png
    - images/return.svg
    - images/product.svg
    - images/add_order.svg
    - images/omi_channel.png
    - images/pos.svg
    - images/moving.svg
    - images/delivery-truck-1.svg
    - images/cart.png
    - images/okiela_logo.png
    - images/scan_barcode.png
    - images/ic_tax.png
    - images/ic_percent.png
    - images/fulltimeship_logo.jpg
    - images/bestshipper_logo.png
    - images/flash_ship_logo.jpg
    - images/dhl_express_logo.jpg
    - images/salary.svg
    - images/invoice.svg
    - images/ic_invoice.png
    - images/quotation.svg
    - images/type_payment.svg
    - images/ic_zalo.png
    - images/ic_map.png
    - images/intro_slide_1.png
    - images/intro_slide_2.png
    - images/intro_slide_3.png
    - images/group_slide_1.png
    - images/group_slide_2.png
    - images/group_slide_3.png
    - images/avatar_tpage.png
    - images/cart_tpage.png
    - images/locattion_tpage.png
    - images/telephone.png
    - images/sort_icon.png
    - images/facebook_icon.png
    - images/facebook_black.png
    - images/empty_data.svg
    - images/connect_with_facebook.png
    - images/facebook_avatar.png
    - images/message_avatar.png
    - assets/icon/ic_cart.svg
    - assets/icon/ic_invoice.svg
    - assets/icon/ic_save_money.svg
    - assets/icon/ic_tag.svg
    - assets/icon/ic_count.svg
    - assets/icon/ic_revenue.svg
    - assets/icon/ic_bag.svg
    - assets/icon/ic_product_warning.svg
    - assets/icon/ic_product_warning_green.svg
    - assets/icon/warning.svg
    - assets/icon/background_money.svg
    - assets/icon/money.svg
    - assets/icon/card.svg
    - assets/icon/ic_state.svg
    - assets/icon/bottom_navigation_icon_home.svg
    - assets/icon/bottom_navigation_icon_report.svg
    - assets/icon/bottom_navigation_notification.svg
    - assets/icon/ic_user.png
    - assets/icon/icon_no_connect.svg
    - assets/icon/ic_ring.svg
    - assets/icon/ic_state_draft.svg
    - assets/icon/deposit.svg
    - assets/icon/empty-image-product.svg
    - assets/game/lucky_wheel/icon/ic_gift.png
    - assets/game/lucky_wheel/icon/ic_user.png
    - lib/feature_group/sale_online/game/icon/ic_open_book.png
    - lib/feature_group/sale_online/game/icon/ic_button_turned.png
    - lib/feature_group/sale_online/game/icon/ic_refresh.png
    - lib/feature_group/sale_online/game/icon/ic_hand.png
    - lib/feature_group/sale_online/game/icon/ic_close.png
    - lib/feature_group/sale_online/game/icon/ic_setting1.png
    - lib/feature_group/sale_online/game/icon/ic_rotate_screen.png
    - assets/game/icon/ic_message.png
    - assets/game/icon/ic_open_book.png
    - assets/game/icon/ic_button_turned.png
    - assets/game/icon/ic_refresh.png
    - assets/game/icon/ic_hand.png
    - assets/game/icon/ic_close.png
    - assets/game/icon/ic_setting1.png
    - assets/game/icon/ic_rotate_screen.png
    - assets/game/icon/ic_logo_vong_quay.png
    - assets/icon/ic_tags.svg
    - assets/icon/ic_reply.svg
    - assets/icon/ic_setting_tpage.svg
    - assets/icon/ic_zalo.svg
    - assets/svg/appbar_background.svg
    - assets/svg/user-multicolor.svg
    - assets/icon/reload.svg
    - assets/icon/no-result.svg
    - assets/icon/icon_fb.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: UVNVan_B
      fonts:
        - asset: fonts/UVNVan_B.TTF
    - family: times.ttf
      fonts:
        - asset: fonts/times.ttf
        - asset: fonts/timesbd.ttf
        - asset: fonts/timesbi.ttf
        - asset: fonts/timesi.ttf
    - family: TPosIcons
      fonts:
        - asset: assets/fonts/TPosIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: false
