/// Flutter icons TPosIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TPosIcons
///      fonts:
///       - asset: fonts/TPosIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class TPosIcons {
  TPosIcons._();

  static const _kFontFam = 'TPosIcons';
  static const _kFontPkg = null;

  static const IconData accessible =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all_conversation_fill =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_fill_blue =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_fill =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_fill_green =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_order_fill =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_fill =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_fill_blue =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear_fill_light_green =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_product_fill =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inventory_fill =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invoice_fill =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live_session_fill =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multi_chanel_fill =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_fill =
      IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pos_session_fill =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pre_order_fill_blue =
      IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product_fill =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotation_fill =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_fill =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData return_icon =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_print_fill =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_sale_fill =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stock_fill =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team_fill =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_dots_horizontal =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_fill_blue =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unit_fill =
      IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_fill =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData variant_fill =
      IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warehouse_fill =
      IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData revenue_fill =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
